# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-11 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukiogram', '0006_auto_20170626_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tukio',
            name='category',
            field=models.CharField(choices=[('corruption', 'Corruption'), ('robbery', 'Robbery'), ('vandalism', 'Vandalism'), ('burglary', 'Burglary'), ('drugUse', 'Drug Use')], max_length=50),
        ),
    ]
