# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-14 11:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukiogram', '0007_auto_20180712_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location_geom', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('helpline', models.CharField(max_length=50)),
            ],
        ),
    ]
